Add booking filtering functionality for manager
eid-sonkrot/Ticket-Booking-System pull request #12
Opened 2023-08-14 18:33 UTC by eid-sonkrot

**Pull Request: Manager Enhancements**

This PR adds key features for the manager role:

1. **Booking Filter**: Manager can filter bookings by flight, price, country, date, airport, passenger, and class.

2. **Bulk Flight Import (CSV)**: Users can import flights via CSV. Model-level validations catch errors, with detailed error reports for easy fixes.

These enhancements streamline manager tasks and improve data quality.

2023-08-28 11:18 UTC, Alatrash814 requested changes

2023-08-28 11:18 UTC, Alatrash814 commented on Ticket Booking System/Business/Booking.cs
> +            ticket.Compare(ticket2))).Count().Equals(tickets.Count());
```suggestion
            var isValid = this.tickets.Count(ticket => booking.tickets.All(ticket.Compare)).Equals(tickets.Count());

```

2023-08-28 11:18 UTC, Alatrash814 commented on Ticket Booking System/Business/Booking.cs
> +            if (!booking.journeyStatus.Equals( this.journeyStatus )&& booking.journeyStatus != null)
```suggestion
if (booking.journeyStatus != null && !booking.journeyStatus.Equals(this.journeyStatus))
```

also please apply this for all the if statements below.

2023-09-15 14:09 UTC, ahmad-m-abbas approved these changes

2023-09-15 14:10 UTC, merged